services:
  # Pi-hole Dienst (wieder aktiviert)
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'password123' # Ändern Sie dies zu einem sicheren Passwort!
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: 172.20.0.100 # Feste IP-Adresse für Pi-hole
    healthcheck:
      test: ["CMD", "pihole-FTL", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    # KORREKTUR: 'dns' ist eine Eigenschaft auf der Hauptebene des Dienstes
    dns:
      - 172.20.0.100
    networks:
      - pihole_network # Nur der Netzwerkname wird hier aufgeführt

  # Selenium Grid Chrome Node 1
  chrome-node-1:
    image: selenium/node-chromium:latest
    container_name: chrome-node-1
    depends_on:
      selenium-hub:
        condition: service_healthy
      pihole:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_ENABLED=true
      - SE_VNC_PORT=7900
      - SE_VNC_NO_PASSWORD=false
      - SE_VNC_PASSWORD=secret
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - SE_START_XVFB=true
    ports:
      - "5900:7900"
    shm_size: "4g"
    # KORREKTUR: 'dns' ist eine Eigenschaft auf der Hauptebene des Dienstes
    dns:
      - 172.20.0.100
    networks:
      - pihole_network # Nur der Netzwerkname wird hier aufgeführt

  # Dein Python-Anwendungs-Container
  video-downloader-app:
    build:
      context: .
      dockerfile: ./docker/python-app/Dockerfile
    image: seriendownloader-app:latest
    container_name: seriendownloader-app
    volumes:
      - ./downloads:/app/Folgen
      - ./app:/app/src
    depends_on:
      selenium-hub:
        condition: service_healthy
      pihole:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
    command: ["python", "/app/src/downloadManager.py", "http://186.2.175.5/redirect/18421293", "/app/Folgen", "--no-headless"]
    # KORREKTUR: 'dns' ist eine Eigenschaft auf der Hauptebene des Dienstes
    dns:
      - 172.20.0.100
    networks:
      - pihole_network # Nur der Netzwerkname wird hier aufgeführt

networks:
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24


