services:
  video-downloader:
    # 'build: .' weist Docker Compose an, das Dockerfile im aktuellen Verzeichnis zu verwenden
    build: . 
    # Der Name des Images, das gebaut wird.
    image: seriendownloader-chromium:latest 
    # Optional: Ein fester Name für deinen Container.
    container_name: seriendownloader 

    # --- Ressourcen-Limits für den Container ---
    # Dies ist wichtig für Performance und Stabilität.
    deploy:
      resources:
        limits:
          memory: 4g  # Maximal 4 GB RAM
          cpus: '2'   # 2 CPU-Kerne

    # --- Shared Memory Größe erhöhen ---
    # Sehr wichtig für Browser in Headless-Umgebungen.
    shm_size: '2g' # 2 GB Shared Memory

    # --- Volume Mapping für persistente Downloads ---
    # Downloads aus dem Container werden auf deinem Host-System gespeichert.
    # Erstelle den Ordner `./downloads` auf deinem Host-System.
    volumes:
      - ./downloads:/app/ausgabe 

    # Der Befehl, der im Container ausgeführt wird (passt zum CMD im Dockerfile)
    command: ["xvfb-run", "--auto-display", "--server-num=1", "--server-args='-screen 0 1920x1080x24'", "python", "downloadManager.py", "https://186.2.175.5/redirect/18366862", "/app/ausgabe"]

    # Optional: Umgebungsvariablen können hier gesetzt werden.
    environment:
      - PYTHONUNBUFFERED=1